### ISSUE TITLE
question/idea for songs with lyrics subtitles

### ISSUE THREAD

**Issue by mandric** [katspaugh/videobook#10]
Hi, I just came across your github and noticed you wrote some amazing tools for dealing with audio and video in the browser and have a somewhat related question/idea.  

Do you think it would be useful to have a web based tool that takes an audio file and some text files (I'm not sure what format exactly but maybe srt/subtitle formats) that can represent lyrics?  My goal is just to have an easy way to understand music in different languages, so you might have a song lyrics in multiple languages being displayed in a web browser.   It goes along with your idea for video book, except for music.  I agree film is a great way to learn languages but so is music (when you include the lyrics/subtitles).  Let me know what you think, it seems this might be a valuable addition to the tool set you are creating here, and I'd be happy to help out.

**Comment by mandric** [comment]
Ok I found something, sorry probably should have searched a bit more.  https://guoyunhe.me/rabbit-lyrics/

**Comment by katspaugh** [comment]
Yeah, that's a nice idea. I'm learning German at the moment, and would also find such a tool useful.

http://wavesurfer-js.org/example/elan/ – this one is close to how `rabbit-lyrics` looks, albeit requires a different format of subtitles.
http://wavesurfer-js.org/example/annotation/ – this one is a tool to manually annotate audios.

You might be also interested in https://github.com/readbeyond/aeneas – it's a brilliant library that automatically generates timed subtitles from any given audio and unparsed text. There are many lyrics on sites like genius.com or songlyrics.com, but they don't have timestamps. Aeneas can solve this problem.

**Comment by mandric** [comment]
Oh wow, yeah the major problem (workload) is manually editing lyrics to add timing.  If there is code to solve or help with that that's a big win.  I'll check out aeneas and keep you updated.  Might also ping the rabbit-lyrics guy to see if he uses something to solve that.  Thanks for your advice.  Even appears to have a web service https://aeneasweb.org/.
