### ISSUE TITLE
Netflix subtitle viewer

### ISSUE THREAD

**Issue by alanbernstein** [katspaugh/videobook#13]
I apologize if this is not the right channel, but I'm writing here because it's the only suggestion at https://wavesurfer-js.org/contact-us/. Please redirect me to email or otherwise if it's more appropriate.

I am trying to find or build a tool for navigating subtitles in Netflix. The prototype shown at https://wavesurfer-js.org/blog/netflix-subs.html is, more or less, exactly what I'm looking for. Is this available in a complete package anywhere public, maybe as a browser extension?

**Comment by katspaugh** [comment]
Sorry, I just saw this question now.

The one from the blog is here: https://github.com/katspaugh/subflix-extension

There's also http://languagelearningwithnetflix.com/
